DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjk3MzQzMjgsInVzZXJJZCI6MX0.W6WP7DaJARPSBfBOwFeVd09H5-wb9w-gGKireuDdZTY