POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjk3MzYwNzksInVzZXJJZCI6MX0.-F8YdabPDokDrt3qhJxp-w_5K5W5ccr7w_sgMdGHwaE

{
    "name": "Test event",
    "description": "test event",
    "location": "a test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}