POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI5NzM2MTI4LCJ1c2VySWQiOjJ9.YJGeTTktZl_Nv-GmBlSFrqkRl0Es2O3mNvNUEsyIgeE